name: surfnet
channels:
  - pytorch-nightly
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - cudatoolkit=9.2
  - opencv
  - pycocotools
  - debugpy
  - scipy
  - tqdm
  - av 
  - tensorboard